// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHvWde_VbdhLWwZQzhEEBhWA0F6QgfzUI',
    appId: '1:563822930417:android:d50a1107a00e52152cfc50',
    messagingSenderId: '563822930417',
    projectId: 'yodoctor-bf82e',
    storageBucket: 'yodoctor-bf82e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXEsSWUbV0KOrgLDlG42npHGN5BWJM31A',
    appId: '1:563822930417:ios:2bf75a8c1aa291b42cfc50',
    messagingSenderId: '563822930417',
    projectId: 'yodoctor-bf82e',
    storageBucket: 'yodoctor-bf82e.firebasestorage.app',
    androidClientId: '563822930417-ffkki8m85h27edg7oadt9o6abv8l1eos.apps.googleusercontent.com',
    iosClientId: '563822930417-1j3mlgqr0m5u6fsa44t59j6ib71sgkch.apps.googleusercontent.com',
    iosBundleId: 'com.yodoctor.app',
  );
}
